import{a as M,i,S as P}from"./assets/vendor-D5mnuR-h.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))n(r);new MutationObserver(r=>{for(const s of r)if(s.type==="childList")for(const u of s.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&n(u)}).observe(document,{childList:!0,subtree:!0});function e(r){const s={};return r.integrity&&(s.integrity=r.integrity),r.referrerPolicy&&(s.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?s.credentials="include":r.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function n(r){if(r.ep)return;r.ep=!0;const s=e(r);fetch(r.href,s)}})();const H="49355863-0bea5bd004f89622601c6cae0",$="https://pixabay.com/api/";let h=1;async function f(t,o=1){try{const e=await M.get($,{params:{key:H,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:15}});return{hits:e.data.hits,totalHits:e.data.totalHits}}catch(e){return console.error("Sorry, there are no images matching your search query. Please try again!",e),i.error({title:"❌ Error",message:"Something went wrong!",position:"topRight"}),{hits:[],totalHits:0}}}function x(t){h=1}function B(){h+=1}function p(){return h}let d;function y(t){const o=document.querySelector(".gallery");t.forEach(e=>{const n=document.createElement("li");n.classList.add("gallery-item"),n.innerHTML=`
        <a href="${e.largeImageURL}" class="gallery-link">
          <img src="${e.webformatURL}" alt="${e.tags}" loading="lazy"/>
        </a>
        <div class="info">
          <p>Likes: ${e.likes}</p>
          <p>Views: ${e.views}</p>
          <p>Comments: ${e.comments}</p>
          <p>Downloads: ${e.downloads}</p>
        </div>
      `,o.appendChild(n)}),d?d.refresh():d=new P(".gallery a",{captions:!0,captionsData:"alt",captionDelay:250})}const L=document.querySelector(".form"),w=document.querySelector(".gallery"),S=document.querySelector(".loader"),m=document.querySelector(".load-more-button"),b=document.querySelector(".message-end");let E="",l=0;const q=40;function v(){S.style.display="block"}function c(){S.style.display="none"}function R(){m.style.display="block"}function a(){m.style.display="none"}function g(){b.style.display="block"}function C(){b.style.display="none"}function I(){const t=w.querySelector(".gallery-item");if(t){const o=t.getBoundingClientRect().height;window.scrollBy({top:o*2,behavior:"smooth"})}}async function N(t){t.preventDefault();const o=L.elements["search-text"].value.trim();if(o===""){i.error({title:"❌ Error",message:"Please enter a search query!",position:"topRight"});return}x(),E=o,l=0,v(),w.innerHTML="",C();try{const{hits:e,totalHits:n}=await f(o,p());c(),e.length===0?(i.error({title:"❌ No images found",message:"Try another search query!",position:"topRight"}),a()):(y(e),l+=e.length,l>=q?(i.success({title:"🎉 Success",message:"You have reached the image limit!",position:"topRight"}),a()):e.length<n?R():(a(),g()),I())}catch{c(),i.error({title:"❌ Error",message:"Something went wrong!",position:"topRight"})}}async function O(){B(),v();try{const{hits:t,totalHits:o}=await f(E,p());c(),t.length>0?(y(t),l+=t.length,l>=q?(i.success({title:"🎉 Success",message:"You have reached the image limit!",position:"topRight"}),a()):t.length<o?R():(a(),g()),I()):(i.error({title:"❌ No more images found",message:"End of results!",position:"topRight"}),a(),g())}catch{c(),i.error({title:"❌ Error",message:"Something went wrong!",position:"topRight"})}}L.addEventListener("submit",N);m.addEventListener("click",O);
//# sourceMappingURL=index.js.map
