import{a as v,i,S as R}from"./assets/vendor-D5mnuR-h.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))s(r);new MutationObserver(r=>{for(const n of r)if(n.type==="childList")for(const u of n.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&s(u)}).observe(document,{childList:!0,subtree:!0});function e(r){const n={};return r.integrity&&(n.integrity=r.integrity),r.referrerPolicy&&(n.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?n.credentials="include":r.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function s(r){if(r.ep)return;r.ep=!0;const n=e(r);fetch(r.href,n)}})();const M="49355863-0bea5bd004f89622601c6cae0",H="https://pixabay.com/api/";let y=1;async function h(t,o=1){try{const e=await v.get(H,{params:{key:M,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:15}});return{hits:e.data.hits,totalHits:e.data.totalHits}}catch(e){return console.error("Sorry, there are no images matching your search query. Please try again!",e),i.error({title:"❌ Error",message:"Something went wrong!",position:"topRight"}),{hits:[],totalHits:0}}}function I(t){y=1}function C(){y+=1}function m(){return y}let d;function p(t){const o=document.querySelector(".gallery");t.forEach(e=>{const s=document.createElement("li");s.classList.add("gallery-item"),s.innerHTML=`
        <a href="${e.largeImageURL}" class="gallery-link">
          <img src="${e.webformatURL}" alt="${e.tags}" loading="lazy"/>
        </a>
        <div class="info">
          <p>Likes: ${e.likes}</p>
          <p>Views: ${e.views}</p>
          <p>Comments: ${e.comments}</p>
          <p>Downloads: ${e.downloads}</p>
        </div>
      `,o.appendChild(s)}),d?d.refresh():d=new R(".gallery a",{captions:!0,captionsData:"alt",captionDelay:250})}function $(){const t=document.querySelector(".gallery");t.innerHTML=""}const w=document.querySelector(".form"),x=document.querySelector(".gallery"),L=document.querySelector(".loader"),f=document.querySelector(".load-more-button"),S=document.querySelector(".message-end");let b="",a=0;function q(){L.style.display="block"}function c(){L.style.display="none"}function E(){f.style.display="block"}function l(){f.style.display="none"}function g(){S.style.display="block"}function B(){S.style.display="none"}function P(){const t=x.querySelector(".gallery-item");if(t){const o=t.getBoundingClientRect().height;window.scrollBy({top:o*2,behavior:"smooth"})}}async function N(t){t.preventDefault();const o=w.elements["search-text"].value.trim();if(o===""){i.error({title:"❌ Error",message:"Please enter a search query!",position:"topRight"});return}I(),b=o,a=0,q(),$(),B(),l();try{const{hits:e,totalHits:s}=await h(o,m());c(),e.length===0?(i.error({title:"❌ No images found",message:"Try another search query!",position:"topRight"}),l()):(p(e),a+=e.length,a>=s?(l(),g()):e.length<s&&E(),P())}catch{c(),i.error({title:"❌ Error",message:"Something went wrong!",position:"topRight"})}}async function O(){C(),q();try{const{hits:t,totalHits:o}=await h(b,m());c(),t.length>0?(p(t),a+=t.length,a>=o?(l(),g()):E(),P()):(i.error({title:"❌ No more images found",message:"End of results!",position:"topRight"}),l(),g())}catch{c(),i.error({title:"❌ Error",message:"Something went wrong!",position:"topRight"})}}w.addEventListener("submit",N);f.addEventListener("click",O);
//# sourceMappingURL=index.js.map
